# Form implementation generated from reading ui file 'applycode.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_enterCoupon(object):
    def setupUi(self, enterCoupon):
        enterCoupon.setObjectName("enterCoupon")
        enterCoupon.resize(271, 129)
        self.label = QtWidgets.QLabel(enterCoupon)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.applycode = QtWidgets.QPushButton(enterCoupon)
        self.applycode.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.applycode.setObjectName("applycode")
        self.widget = QtWidgets.QWidget(enterCoupon)
        self.widget.setGeometry(QtCore.QRect(30, 60, 191, 31))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.codecoupon = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.codecoupon.setFont(font)
        self.codecoupon.setObjectName("codecoupon")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.codecoupon)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)

        self.retranslateUi(enterCoupon)
        QtCore.QMetaObject.connectSlotsByName(enterCoupon)

    def retranslateUi(self, enterCoupon):
        _translate = QtCore.QCoreApplication.translate
        enterCoupon.setWindowTitle(_translate("enterCoupon", "applycode"))
        self.label.setText(_translate("enterCoupon", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Enter your Coupon number :</span></p></body></html>"))
        self.applycode.setText(_translate("enterCoupon", "Apply"))
        self.codecoupon.setText(_translate("enterCoupon", "Code Coupon"))
        self.lineEdit.setPlaceholderText(_translate("enterCoupon", "discount code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    enterCoupon = QtWidgets.QWidget()
    ui = Ui_enterCoupon()
    ui.setupUi(enterCoupon)
    enterCoupon.show()
    sys.exit(app.exec())
