# Form implementation generated from reading ui file 'changeinfo.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_changeprofile(object):
    def setupUi(self, changeprofile):
        changeprofile.setObjectName("changeprofile")
        changeprofile.resize(400, 194)
        self.label_4 = QtWidgets.QLabel(changeprofile)
        self.label_4.setGeometry(QtCore.QRect(110, 10, 171, 41))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(changeprofile)
        self.widget.setGeometry(QtCore.QRect(250, 50, 118, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.widget1 = QtWidgets.QWidget(changeprofile)
        self.widget1.setGeometry(QtCore.QRect(24, 49, 211, 120))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.retranslateUi(changeprofile)
        QtCore.QMetaObject.connectSlotsByName(changeprofile)

    def retranslateUi(self, changeprofile):
        _translate = QtCore.QCoreApplication.translate
        changeprofile.setWindowTitle(_translate("changeprofile", "changeprofile"))
        self.label_4.setText(_translate("changeprofile", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Personal Info</span></p><p align=\"center\"><span style=\" font-size:14pt;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("changeprofile", "Enter your new Email :"))
        self.label_2.setText(_translate("changeprofile", "Enter you\'r new Password :"))
        self.label_3.setText(_translate("changeprofile", "Confirm  Your New Password :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changeprofile = QtWidgets.QWidget()
    ui = Ui_changeprofile()
    ui.setupUi(changeprofile)
    changeprofile.show()
    sys.exit(app.exec())
