# Form implementation generated from reading ui file 'confirmlogout.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_confirmlogout(object):
    def setupUi(self, confirmlogout):
        confirmlogout.setObjectName("confirmlogout")
        confirmlogout.resize(224, 111)
        self.label = QtWidgets.QLabel(confirmlogout)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(confirmlogout)
        self.widget.setGeometry(QtCore.QRect(20, 51, 181, 54))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cancellogout = QtWidgets.QPushButton(self.widget)
        self.cancellogout.setObjectName("cancellogout")
        self.verticalLayout.addWidget(self.cancellogout)
        self.confirmlogout_2 = QtWidgets.QPushButton(self.widget)
        self.confirmlogout_2.setObjectName("confirmlogout_2")
        self.verticalLayout.addWidget(self.confirmlogout_2)

        self.retranslateUi(confirmlogout)
        QtCore.QMetaObject.connectSlotsByName(confirmlogout)

    def retranslateUi(self, confirmlogout):
        _translate = QtCore.QCoreApplication.translate
        confirmlogout.setWindowTitle(_translate("confirmlogout", "confirmlogout"))
        self.label.setText(_translate("confirmlogout", "Are you sure you want to log out :"))
        self.cancellogout.setText(_translate("confirmlogout", "Cancel"))
        self.confirmlogout_2.setToolTip(_translate("confirmlogout", "<html><head/><body><p><span style=\" color:#ff0000;\">Logout</span></p><p><span style=\" color:#ff0000;\"><br/></span></p></body></html>"))
        self.confirmlogout_2.setText(_translate("confirmlogout", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirmlogout = QtWidgets.QWidget()
    ui = Ui_confirmlogout()
    ui.setupUi(confirmlogout)
    confirmlogout.show()
    sys.exit(app.exec())
