# Form implementation generated from reading ui file 'consumerrprofile.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from applycode import Ui_enterCoupon
from confirmlogout import Ui_confirmlogout
from changeinfo import Ui_changeprofile

class Ui_Costumerprofile(object):
    def openscoupon(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_enterCoupon()
        self.ui.setupUi(self.window)
        Costumerprofile.close()
        self.window.show()

    def openlogout(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_confirmlogout()
        self.ui.setupUi(self.window)
        Costumerprofile.close()
        self.window.show()

    def openaccinfo(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_changeprofile()
        self.ui.setupUi(self.window)
        Costumerprofile.close()
        self.window.show()

    def setupUi(self, Costumerprofile):
        Costumerprofile.setObjectName("Costumerprofile")
        Costumerprofile.resize(378, 233)
        Costumerprofile.setStyleSheet("")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Costumerprofile)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, -40, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Couponcost = QtWidgets.QPushButton(Costumerprofile)
        self.Couponcost.setGeometry(QtCore.QRect(150, 110, 75, 23))
        self.Couponcost.setObjectName("Couponcost")
        self.welcomemsg = QtWidgets.QLabel(Costumerprofile)
        self.welcomemsg.setGeometry(QtCore.QRect(100, 0, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.welcomemsg.setFont(font)
        self.welcomemsg.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.welcomemsg.setObjectName("welcomemsg")
        self.label_3 = QtWidgets.QLabel(Costumerprofile)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 129, 33))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.sumpoint = QtWidgets.QLabel(Costumerprofile)
        self.sumpoint.setGeometry(QtCore.QRect(40, 180, 100, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sumpoint.setFont(font)
        self.sumpoint.setObjectName("sumpoint")
        self.Logoutcost = QtWidgets.QPushButton(Costumerprofile)
        self.Logoutcost.setGeometry(QtCore.QRect(150, 139, 75, 23))
        self.Logoutcost.setObjectName("Logoutcost")
        self.profilecost = QtWidgets.QPushButton(Costumerprofile)
        self.profilecost.setGeometry(QtCore.QRect(150, 52, 75, 23))
        self.profilecost.setStyleSheet("")
        self.profilecost.setObjectName("profilecost")
        self.collectioncost = QtWidgets.QPushButton(Costumerprofile)
        self.collectioncost.setGeometry(QtCore.QRect(150, 81, 75, 23))
        self.collectioncost.setObjectName("collectioncost")
        self.Couponcost.clicked.connect(self.openscoupon)
        self.Logoutcost.clicked.connect(self.openlogout)
        self.profilecost.clicked.connect(self.openaccinfo)

        self.retranslateUi(Costumerprofile)
        QtCore.QMetaObject.connectSlotsByName(Costumerprofile)

    def retranslateUi(self, Costumerprofile):
        _translate = QtCore.QCoreApplication.translate
        Costumerprofile.setWindowTitle(_translate("Costumerprofile", "Costumerprofile"))
        self.Couponcost.setText(_translate("Costumerprofile", "Coupon"))
        self.welcomemsg.setText(_translate("Costumerprofile", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400; font-style:italic; color:#000000;\">Welcome back </span></p></body></html>"))
        self.sumpoint.setText(_translate("Costumerprofile", "Your Point :"))
        self.Logoutcost.setText(_translate("Costumerprofile", "Logout"))
        self.profilecost.setText(_translate("Costumerprofile", "Profile "))
        self.collectioncost.setText(_translate("Costumerprofile", "Collection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Costumerprofile = QtWidgets.QWidget()
    ui = Ui_Costumerprofile()
    ui.setupUi(Costumerprofile)
    Costumerprofile.show()
    sys.exit(app.exec())
