import sqlite3

u = 'asd'
mail = 'dasf@'
pw = '123'
prof = 'Volunteer'

db = sqlite3.connect('hAppDB.db')
print("Opened database successfully")
cursor = db.cursor()
cursor.execute("INSERT INTO users (Username,Email,Password,Profile) VALUES (?,?,?,'Volunteer')", (u, mail, pw))
db.commit()
print("Records created successfully")
db.close()



###############################
# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from login import Ui_login
from signup import Ui_create

class Ui_welcomescreen(object):
    def opensignin(self):
        self.window= QtWidgets.QWidget()
        self.ui= Ui_login()
        self.ui.setupUi(self.window)
        self.window.show()

    def opensignup(self):
        self.windowup= QtWidgets.QWidget()
        self.ui= Ui_create()
        self.ui.setupUi(self.windowup)
        self.windowup.show()

    def setupUi(self, welcomescreen):
        welcomescreen.setObjectName("welcomescreen")
        welcomescreen.resize(388, 300)
        self.gridLayout = QtWidgets.QGridLayout(welcomescreen)
        self.gridLayout.setObjectName("gridLayout")
        self.welcomeL = QtWidgets.QLabel(welcomescreen)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.welcomeL.setFont(font)
        self.welcomeL.setObjectName("welcomeL")
        self.gridLayout.addWidget(self.welcomeL, 0, 0, 1, 1)
        self.signL = QtWidgets.QLabel(welcomescreen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.signL.setFont(font)
        self.signL.setObjectName("signL")
        self.gridLayout.addWidget(self.signL, 1, 0, 1, 1)
        self.login = QtWidgets.QPushButton(welcomescreen)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 2, 0, 1, 1)
        self.createacc = QtWidgets.QPushButton(welcomescreen)
        self.createacc.setObjectName("createacc")
        self.gridLayout.addWidget(self.createacc, 3, 0, 1, 1)
        self.login.clicked.connect(self.opensignin)
        self.createacc.clicked.connect(self.opensignup)


        self.retranslateUi(welcomescreen)
        QtCore.QMetaObject.connectSlotsByName(welcomescreen)


    def retranslateUi(self, welcomescreen):
        _translate = QtCore.QCoreApplication.translate
        welcomescreen.setWindowTitle(_translate("welcomescreen", "Form"))
        self.welcomeL.setText(_translate("welcomescreen", "welcome "))
        self.signL.setText(_translate("welcomescreen", "Sign in or make a new account"))
        self.login.setText(_translate("welcomescreen", "Login "))
        self.createacc.setText(_translate("welcomescreen", "Creat a new account"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcomescreen = QtWidgets.QWidget()
    ui = Ui_welcomescreen()
    ui.setupUi(welcomescreen)
    welcomescreen.show()
    sys.exit(app.exec())
################################
# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(375, 236)
        self.loginL = QtWidgets.QPushButton(login)
        self.loginL.setGeometry(QtCore.QRect(120, 180, 75, 23))
        self.loginL.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.loginL.setObjectName("loginL")
        self.unL = QtWidgets.QLabel(login)
        self.unL.setGeometry(QtCore.QRect(80, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unL.setFont(font)
        self.unL.setObjectName("unL")
        self.pwL = QtWidgets.QLabel(login)
        self.pwL.setGeometry(QtCore.QRect(80, 130, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pwL.setFont(font)
        self.pwL.setObjectName("pwL")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(130, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 171, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(169, 90, 151, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameLF = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.usernameLF.setObjectName("usernameLF")
        self.verticalLayout.addWidget(self.usernameLF)
        self.passwordLF = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLF.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLF.setObjectName("passwordLF")
        self.verticalLayout.addWidget(self.passwordLF)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.loginL.setToolTip(_translate("login", "Press To Login "))
        self.loginL.setText(_translate("login", "Login"))
        self.unL.setText(_translate("login", "User Name"))
        self.pwL.setText(_translate("login", "Password"))
        self.label.setText(_translate("login", "Login"))
        self.label_2.setText(_translate("login", "Sign in to your existing account"))
        self.usernameLF.setPlaceholderText(_translate("login", "User name "))
        self.passwordLF.setPlaceholderText(_translate("login", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QWidget()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec())

    ###############################################
    # Form implementation generated from reading ui file 'signup.ui'
    #
    # Created by: PyQt6 UI code generator 6.1.0
    #
    # WARNING: Any manual changes made to this file will be lost when pyuic6 is
    # run again.  Do not edit this file unless you know what you are doing.
    import sqlite3

    from PyQt6 import QtCore, QtGui, QtWidgets


    class Ui_create(object):
        def setupUi(self, create):
            create.setObjectName("create")
            create.resize(475, 301)
            self.signupR = QtWidgets.QPushButton(create)
            self.signupR.setGeometry(QtCore.QRect(200, 240, 75, 31))
            font = QtGui.QFont()
            font.setPointSize(12)
            self.signupR.setFont(font)
            self.signupR.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
            self.signupR.setObjectName("signupR")
            self.signupL = QtWidgets.QLabel(create)
            self.signupL.setGeometry(QtCore.QRect(190, 20, 101, 51))
            font = QtGui.QFont()
            font.setPointSize(22)
            self.signupL.setFont(font)
            self.signupL.setObjectName("signupL")
            self.layoutWidget = QtWidgets.QWidget(create)
            self.layoutWidget.setGeometry(QtCore.QRect(90, 80, 167, 151))
            self.layoutWidget.setObjectName("layoutWidget")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setObjectName("verticalLayout")
            self.unR = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.unR.setFont(font)
            self.unR.setObjectName("unR")
            self.verticalLayout.addWidget(self.unR)
            self.emailR = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.emailR.setFont(font)
            self.emailR.setObjectName("emailR")
            self.verticalLayout.addWidget(self.emailR)
            self.pwR = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.pwR.setFont(font)
            self.pwR.setObjectName("pwR")
            self.verticalLayout.addWidget(self.pwR)
            self.pwcR = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.pwcR.setFont(font)
            self.pwcR.setObjectName("pwcR")
            self.verticalLayout.addWidget(self.pwcR)
            self.profR = QtWidgets.QLabel(self.layoutWidget)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.profR.setFont(font)
            self.profR.setObjectName("profR")
            self.verticalLayout.addWidget(self.profR)
            self.layoutWidget1 = QtWidgets.QWidget(create)
            self.layoutWidget1.setGeometry(QtCore.QRect(260, 80, 135, 151))
            self.layoutWidget1.setObjectName("layoutWidget1")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
            self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            self.usernameRF = QtWidgets.QLineEdit(self.layoutWidget1)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.usernameRF.setFont(font)
            self.usernameRF.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
            self.usernameRF.setObjectName("usernameRF")
            self.verticalLayout_2.addWidget(self.usernameRF)
            self.emailRF = QtWidgets.QLineEdit(self.layoutWidget1)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.emailRF.setFont(font)
            self.emailRF.setObjectName("emailRF")
            self.verticalLayout_2.addWidget(self.emailRF)
            self.pwRF = QtWidgets.QLineEdit(self.layoutWidget1)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.pwRF.setFont(font)
            self.pwRF.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            self.pwRF.setObjectName("pwRF")
            self.verticalLayout_2.addWidget(self.pwRF)
            self.pwcRF = QtWidgets.QLineEdit(self.layoutWidget1)
            font = QtGui.QFont()
            font.setPointSize(10)
            self.pwcRF.setFont(font)
            self.pwcRF.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            self.pwcRF.setObjectName("pwcRF")
            self.verticalLayout_2.addWidget(self.pwcRF)
            self.profboxR = QtWidgets.QComboBox(self.layoutWidget1)
            self.profboxR.setEnabled(True)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.profboxR.setFont(font)
            self.profboxR.setEditable(False)
            self.profboxR.setFrame(True)
            self.profboxR.setObjectName("profboxR")
            self.profboxR.addItem("")
            self.profboxR.addItem("")
            self.verticalLayout_2.addWidget(self.profboxR)
            self.signupR.clicked.connect(self.createacc)
            self.retranslateUi(create)
            QtCore.QMetaObject.connectSlotsByName(create)

        def createacc(self):
            u = self.usernameRF.text()
            mail = self.emailRF.text()
            pw = self.pwRF.text()
            pwc = self.pwcRF.text()
            prof = self.profboxR.currentText()
            if len(u) == 0 or len(pw) == 0 or len(pwc) == 0:
                self.error.setText("Please fill in all inputs.")

            elif pw != pwc:
                self.error.setText("Passwords do not match.")
            else:
                db = sqlite3.connect('hAppDB.db')
                print("Opened database successfully")
                cursor = db.cursor()
                cursor.execute("INSERT INTO users (Username,Email,Password,Profile) VALUES (?,?,?,?)",
                               (u, mail, pw, prof))
                db.commit()
                print("Records created successfully")
                db.close()

        def retranslateUi(self, create):
            _translate = QtCore.QCoreApplication.translate
            create.setWindowTitle(_translate("create", "Form"))
            self.signupR.setToolTip(_translate("create", "Press To Signup"))
            self.signupR.setText(_translate("create", "Signup"))
            self.signupL.setText(_translate("create", "Signup"))
            self.unR.setText(_translate("create", "User Name"))
            self.emailR.setText(_translate("create", "Email"))
            self.pwR.setText(_translate("create", "Password"))
            self.pwcR.setText(_translate("create", "Password Confirm "))
            self.profR.setText(_translate("create", "Profile"))
            self.usernameRF.setPlaceholderText(_translate("create", "Enter Your Name "))
            self.emailRF.setPlaceholderText(_translate("create", "Enter Your  Email"))
            self.pwRF.setPlaceholderText(_translate("create", "Enter Your Password"))
            self.pwcRF.setPlaceholderText(_translate("create", "Password Confirm "))
            self.profboxR.setCurrentText(_translate("create", "volunteer"))
            self.profboxR.setItemText(0, _translate("create", "volunteer"))
            self.profboxR.setItemText(1, _translate("create", "Consumer"))


    if __name__ == "__main__":
        import sys

        app = QtWidgets.QApplication(sys.argv)
        create = QtWidgets.QWidget()
        ui = Ui_create()
        ui.setupUi(create)
        create.show()
        sys.exit(app.exec())


