# Form implementation generated from reading ui file 'volunteerprofile.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from confirmlogout import Ui_confirmlogout
from changeinfo import Ui_changeprofile

class Ui_volunteerprofile(object):
    def openlogout(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_confirmlogout()
        self.ui.setupUi(self.window)
        volunteerprofile.close()
        self.window.show()


    def openaccinfo(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_changeprofile()
        self.ui.setupUi(self.window)
        volunteerprofile.close()
        self.window.show()

    def setupUi(self, volunteerprofile):
        volunteerprofile.setObjectName("volunteerprofile")
        volunteerprofile.resize(428, 235)
        volunteerprofile.setStyleSheet("")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(volunteerprofile)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, -40, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcomemsg = QtWidgets.QLabel(volunteerprofile)
        self.welcomemsg.setGeometry(QtCore.QRect(8, 13, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.welcomemsg.setFont(font)
        self.welcomemsg.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.welcomemsg.setObjectName("welcomemsg")
        self.pushlogout = QtWidgets.QPushButton(volunteerprofile)
        self.pushlogout.setGeometry(QtCore.QRect(290, 92, 141, 61))
        self.pushlogout.setObjectName("pushlogout")
        self.pushprofile = QtWidgets.QPushButton(volunteerprofile)
        self.pushprofile.setGeometry(QtCore.QRect(290, 1, 141, 51))
        self.pushprofile.setStyleSheet("")
        self.pushprofile.setObjectName("pushprofile")
        self.collection = QtWidgets.QPushButton(volunteerprofile)
        self.collection.setGeometry(QtCore.QRect(290, 50, 141, 51))
        self.collection.setObjectName("collection")
        self.sumtotal = QtWidgets.QLabel(volunteerprofile)
        self.sumtotal.setGeometry(QtCore.QRect(10, 200, 107, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sumtotal.setFont(font)
        self.sumtotal.setObjectName("sumtotal")
        self.filler1 = QtWidgets.QLabel(volunteerprofile)
        self.filler1.setGeometry(QtCore.QRect(130, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filler1.setFont(font)
        self.filler1.setObjectName("filler1")
        self.sumpoint = QtWidgets.QLabel(volunteerprofile)
        self.sumpoint.setGeometry(QtCore.QRect(10, 130, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sumpoint.setFont(font)
        self.sumpoint.setObjectName("sumpoint")
        self.filler2 = QtWidgets.QLabel(volunteerprofile)
        self.filler2.setGeometry(QtCore.QRect(130, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.filler2.setFont(font)
        self.filler2.setObjectName("filler2")

        self.retranslateUi(volunteerprofile)
        QtCore.QMetaObject.connectSlotsByName(volunteerprofile)
        self.pushlogout.clicked.connect(self.openlogout)
        self.pushprofile.clicked.connect(self.openaccinfo)

    def retranslateUi(self, volunteerprofile):
        _translate = QtCore.QCoreApplication.translate
        volunteerprofile.setWindowTitle(_translate("volunteerprofile", "volunteerprofile"))
        self.welcomemsg.setText(_translate("volunteerprofile", "<html><head/><body><p><span style=\" font-style:italic; color:#55aaff;\">welcome back </span></p></body></html>"))
        self.pushlogout.setText(_translate("volunteerprofile", "Logout"))
        self.pushprofile.setText(_translate("volunteerprofile", "Profile "))
        self.collection.setText(_translate("volunteerprofile", "Collection"))
        self.sumtotal.setText(_translate("volunteerprofile", "Total hours :"))
        self.filler1.setText(_translate("volunteerprofile", "7"))
        self.sumpoint.setText(_translate("volunteerprofile", "Your Point :"))
        self.filler2.setText(_translate("volunteerprofile", "9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    volunteerprofile = QtWidgets.QWidget()
    ui = Ui_volunteerprofile()
    ui.setupUi(volunteerprofile)
    volunteerprofile.show()
    sys.exit(app.exec())
