# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from login import Ui_login
from signup import Ui_create

class Ui_welcomescreen(object):
    def opensignin(self):
        self.window= QtWidgets.QWidget()
        self.ui= Ui_login()
        self.ui.setupUi(self.window)
        welcomescreen.close()
        self.window.show()

    def opensignup(self):
        self.windowup= QtWidgets.QWidget()
        self.ui= Ui_create()
        self.ui.setupUi(self.windowup)
        welcomescreen.close()
        self.windowup.show()


    def setupUi(self, welcomescreen):
        welcomescreen.setObjectName("welcomescreen")
        welcomescreen.resize(388, 300)
        self.gridLayout = QtWidgets.QGridLayout(welcomescreen)
        self.gridLayout.setObjectName("gridLayout")
        self.welcomeL = QtWidgets.QLabel(welcomescreen)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.welcomeL.setFont(font)
        self.welcomeL.setObjectName("welcomeL")
        self.gridLayout.addWidget(self.welcomeL, 0, 0, 1, 1)
        self.signL = QtWidgets.QLabel(welcomescreen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.signL.setFont(font)
        self.signL.setObjectName("signL")
        self.gridLayout.addWidget(self.signL, 1, 0, 1, 1)
        self.login = QtWidgets.QPushButton(welcomescreen)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 2, 0, 1, 1)
        self.createacc = QtWidgets.QPushButton(welcomescreen)
        self.createacc.setObjectName("createacc")
        self.gridLayout.addWidget(self.createacc, 3, 0, 1, 1)
        self.login.clicked.connect(self.opensignin)
        self.createacc.clicked.connect(self.opensignup)
        self.retranslateUi(welcomescreen)
        QtCore.QMetaObject.connectSlotsByName(welcomescreen)



    def retranslateUi(self, welcomescreen):
        _translate = QtCore.QCoreApplication.translate
        welcomescreen.setWindowTitle(_translate("welcomescreen", "welcome"))
        self.welcomeL.setText(_translate("welcomescreen", "welcome "))
        self.signL.setText(_translate("welcomescreen", "Sign in or make a new account"))
        self.login.setText(_translate("welcomescreen", "Login "))
        self.createacc.setText(_translate("welcomescreen", "Creat a new account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcomescreen = QtWidgets.QWidget()
    ui = Ui_welcomescreen()
    ui.setupUi(welcomescreen)
    welcomescreen.show()
    sys.exit(app.exec())
